require: rubocop-rspec

# We are using default RuboCop settings.
# We are writing beautiful code.
# There is nothing to change here. At least now.
AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  ExtraDetails: true
  RSpec:
    Patterns:
    - '_spec.rb$'

# Ignore block length in DSLs using blocks extensively
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Exclude:

Metrics/MethodLength:
  Exclude:
  # RSpec DSL
  - '**/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
  # RSpec DSL
  - spec/**/*.rb

Metrics/AbcSize:
  Exclude:
  # RSpec DSL
  - '**/spec/**/*.rb'
  - 'app/views/**/*.rb'

Metrics/LineLength:
  Max: 120

# Use UTF-8 as the source file encoding, specify when needed.
Style/Encoding:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/MixinGrouping:
  Exclude:
  # RSpec DSL
  - '**/spec/**/*.rb'

Style/MixinUsage:
  Exclude:
  # Rake DSL
  - '**/rake/**/*.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/Loop:
  Enabled: false

# Rubocop Rspec rules
RSpec/AnyInstance:
  Enabled: false # Should be turned ON eventually

RSpec/ContextWording:
  Enabled: false # Should be turned ON eventually

RSpec/DescribeClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false # Should be turned ON eventually

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: true

RSpec/ExpectActual:
  Enabled: true

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/ExpectOutput:
  Enabled: true

RSpec/FilePath:
  Enabled: true
  Exclude:
    - '**/spec/**/*.rb'

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/LeadingSubject:
  Enabled: true

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

RSpec/ScatteredLet:
  Enabled: false

RSpec/SingleArgumentMessageChain:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: false # Should be turned ON eventually

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false # Should be turned ON eventually
