version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  rubocop: hanachin/rubocop@0.0.6

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - ruby/bundle-install

workflows:
  test:
    jobs:
      - rubocop/rubocop
  version: 2
